spring:
  application:
    name: user
  datasource:
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/sgw?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
      username: root
      password: mysqlpw
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/write?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
      username: root
      password: mysqlpw
  main:
    allow-circular-references: true

mybatis:
  mapper-locations: classpath:/mapper/**.xml

logging:
  level:
    com.sgw: debug
